# Generated by Django 2.2.5 on 2019-09-20 19:25

from django.db import migrations, models
import django.db.models.deletion
import lab_web.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contacts', models.CharField(blank=True, max_length=100)),
                ('comment', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Clinics',
            },
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contacts', models.CharField(blank=True, max_length=100)),
                ('comment', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Doctors',
            },
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(choices=[('gr', 'гр.'), ('sht', 'шт.')], max_length=100)),
                ('limit', models.IntegerField()),
                ('comment', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Materials',
            },
        ),
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Operations',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=100)),
                ('progress', models.CharField(choices=[('NR', 'Не готов'), ('HR', 'Частично готов'), ('R', 'Готов')], max_length=100)),
                ('deadline', models.DateField()),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_web.Clinics')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_web.Doctors')),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Technicians',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contacts', models.CharField(blank=True, max_length=100)),
                ('comment', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Technicians',
            },
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Works',
            },
        ),
        migrations.CreateModel(
            name='WorksPriceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_list', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('clinic', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='lab_web.Clinics')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_web.Works')),
            ],
            options={
                'verbose_name_plural': 'Works Price Lists',
            },
        ),
        migrations.CreateModel(
            name='WorkInOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_web.Orders')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_web.Works')),
            ],
            options={
                'verbose_name_plural': 'Work In Orders',
            },
        ),
        migrations.CreateModel(
            name='OperationsPriceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_web.Operations')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_web.Technicians')),
            ],
            options={
                'verbose_name_plural': 'Operations Price Lists',
            },
        ),
        migrations.CreateModel(
            name='OperationsInWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_web.Operations')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_web.Works')),
            ],
            options={
                'verbose_name_plural': 'Operations In Works',
            },
        ),
        migrations.CreateModel(
            name='OperationsInOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('deadline', models.DateField()),
                ('is_done', models.BooleanField()),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_web.Operations')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_web.Orders')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_web.Technicians')),
            ],
            options={
                'verbose_name_plural': 'Operation In Orders',
            },
        ),
        migrations.CreateModel(
            name='MaterialUsedOnOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_web.Materials')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_web.Operations')),
            ],
            options={
                'verbose_name_plural': 'Materials Used on Operation',
            },
        ),
        migrations.CreateModel(
            name='MaterialsOnStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_web.Materials')),
            ],
            options={
                'verbose_name_plural': 'Materials On Stock',
            },
        ),
        migrations.CreateModel(
            name='FilesInOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=lab_web.models.get_file_path)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_web.Orders')),
            ],
            options={
                'verbose_name_plural': 'Files In Orders',
            },
        ),
    ]
